REM Index created on 16/03/2003
REM Some Indexes are repeated 2 or 3 times so they are commented
--------------------------------------------------------------------------------
REM  DROP Index Recommendations
--------------------------------------------------------------------------------

DROP INDEX LIFEPROD.PIX_PH_GM_POL_EMPLOYEE;

DROP INDEX LIFEPROD.PIX_PT_GM_CLAIM_1;

DROP INDEX LIFEPROD.PIX_PT_GM_CLAIM_2;

DROP INDEX LIFEPROD.PIX_PT_GM_CLAIM_EMP_1;

DROP INDEX LIFEPROD.PIX_PT_GM_CLAIM_PAID;

--DROP INDEX PREMPROD.PIX_POL_6;

DROP INDEX LIFEPROD.PIX_PH_GM_POLICY;

--DROP INDEX LIFEPROD.PIX_PH_GM_POL_EMPLOYEE;

DROP INDEX LIFEPROD.PIX_ADS_2;

--DROP INDEX LIFEPROD.PIX_PT_GM_CLAIM_1;

--DROP INDEX LIFEPROD.PIX_PT_GM_CLAIM_2;

DROP INDEX LIFEPROD.PIX_PT_GM_CLAIM_DEDUCTIBLE;

--DROP INDEX LIFEPROD.PIX_PT_GM_CLAIM_EMP_1;

DROP INDEX LIFEPROD.PIX_PT_GM_CLAIM_ESTIMATE;

--DROP INDEX LIFEPROD.PIX_PT_GM_CLAIM_PAID;

DROP INDEX LIFEPROD.PIX_PT_GM_POL_BENEFIT_2;

DROP INDEX LIFEPROD.PIX_PT_GM_POL_EMPLOYEE;

--DROP INDEX LIFEPROD.PIX_PT_GM_CLAIM_2;

--DROP INDEX LIFEPROD.PIX_PT_GM_CLAIM_EMP_1;

--DROP INDEX LIFEPROD.PIX_PT_GM_CLAIM_PAID;

DROP INDEX PREMPROD.AIR_POL_SYS_ID;

DROP INDEX PREMPROD.FK_CE_CLM_IDX;

DROP INDEX PREMPROD.PIX_CP_3;

DROP INDEX PREMPROD.OP_POL_SYS_ID;

DROP INDEX PREMPROD.FK_POL_SC_IDX;

--DROP INDEX PREMPROD.PIX_POL_6;

DROP INDEX PREMPROD.FK_PCVR_CURR_IDX;

DROP INDEX PREMPROD.PCVR_POL_SYS_ID;

DROP INDEX PREMPROD.RISK_POL_SYS_ID;

DROP INDEX PREMPROD.SHIP_POL_SYS_ID;

DROP INDEX PREMPROD.SG_SHIP_SYS_ID;

DROP INDEX PREMPROD.PIX_SG_2;

DROP INDEX PREMPROD.VEH_POL_SYS_ID;

DROP INDEX PREMPROD.VES_POL_SYS_ID;

--DROP INDEX PREMPROD.FK_CE_CLM_IDX;

--DROP INDEX PREMPROD.PIX_CP_3;

--DROP INDEX PREMPROD.FK_POL_SC_IDX;


--------------------------------------------------------------------------------
--  CREATE Index Recommendations
--------------------------------------------------------------------------------


CREATE INDEX LIFEPROD.PH_GL_POL_OCC_CATG_IDX_019
     ON LIFEPROD.PH_GL_POL_OCC_CATG
        (POCH_POL_SYS_ID,
         POCH_END_NO_IDX,
         POCH_SYS_ID)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX LIFEPROD.PIX_PH_GM_POL_EMPLOYEE
     ON LIFEPROD.PH_GM_POL_EMPLOYEE
        (PEMPH_SYS_ID,
         PEMPH_END_NO_IDX,
         PEMPH_POLGM_SYS_ID,
         PEMPH_O_NAME)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 9612K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX LIFEPROD.PH_GM_POL_EMPLOYEE_IDX_007
     ON LIFEPROD.PH_GM_POL_EMPLOYEE
        (PEMPH_POLGM_SYS_ID,
         PEMPH_N_EMP_ID,
         PEMPH_N_NAME)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX LIFEPROD.PH_GM_POL_SUB_BENEFI_IDX_005
     ON LIFEPROD.PH_GM_POL_SUB_BENEFIT
        (PSBNFH_PBNF_SYS_ID,
         PSBNFH_N_SBNF_CODE,
         PSBNFH_END_NO_IDX,
         PSBNFH_N_LC_LIMIT)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX LIFEPROD.PS_GL_DRCR_IDX_012
     ON LIFEPROD.PS_GL_DRCR
        (DRCR_POL_SYS_ID,
         DRCR_CUST_CODE,
         DRCR_INT_ENT_YN,
         DRCR_END_NO_IDX,
         DRCR_DOC_NO)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX LIFEPROD.PS_GL_PREM_REG_IDX_017
     ON LIFEPROD.PS_GL_PREM_REG
        (PR_POL_SYS_ID,
         PR_END_NO_IDX,
         PR_LC_SA,
         PR_GROSS_LC_PREM)
    TABLESPACE FIN7IDXTAB
    PCTFREE 10;

CREATE INDEX LIFEPROD.PS_GM_DRCR_IDX_016
     ON LIFEPROD.PS_GM_DRCR
        (DRCR_DOC_DT,
         DRCR_SUB_ACNT_CODE,
         DRCR_CLM_SYS_ID,
         DRCR_TXN_CODE,
         DRCR_DOC_NO)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE UNIQUE INDEX LIFEPROD.PT_GL_POLICY_IDX_018
     ON LIFEPROD.PT_GL_POLICY
        (POL_SYS_ID,
         POL_END_NO_IDX,
         POL_END_TYPE)
    TABLESPACE LIFE
    PCTFREE 10;

CREATE INDEX LIFEPROD.PT_GL_POLICY_IDX_020
     ON LIFEPROD.PT_GL_POLICY
        (POL_DS_CODE,
         POL_SYS_ID)
    TABLESPACE LIFE
    PCTFREE 10;

CREATE INDEX LIFEPROD.PT_GL_POL_AMT_PAYABL_IDX_010
     ON LIFEPROD.PT_GL_POL_AMT_PAYABLE
        (PAP_POL_SYS_ID)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX LIFEPROD.PIX_PT_GM_CLAIM_1
     ON LIFEPROD.PT_GM_CLAIM
        (CLM_POLGM_SYS_ID,
         CLM_SYS_ID)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 60K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX LIFEPROD.PIX_PT_GM_CLAIM_2
     ON LIFEPROD.PT_GM_CLAIM
        (CLM_POL_NO,
         CLM_SYS_ID,
         CLM_CLM_NO)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 60K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX LIFEPROD.PIX_PT_GM_CLAIM_EMP_1
     ON LIFEPROD.PT_GM_CLAIM_EMP
        (CEMP_CLM_SYS_ID,
         CEMP_SYS_ID,
         CEMP_PEMP_SYS_ID,
         CEMP_PEMPD_SYS_ID,
         CEMP_DOA,
         CEMP_FC_NET_CLM_PAID,
         CEMP_REF_NO)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 852K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX LIFEPROD.PT_GM_CLAIM_EMP_IDX_001
     ON LIFEPROD.PT_GM_CLAIM_EMP
        (CEMP_DOA,
         CEMP_FC_NET_CLM_PAID,
         CEMP_REF_NO)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX LIFEPROD.PT_GM_CLAIM_EMP_IDX_015
     ON LIFEPROD.PT_GM_CLAIM_EMP
        (CEMP_REF_NO,
         CEMP_CLM_SYS_ID,
         CEMP_DOA,
         CEMP_PEMP_EMP_ID)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX LIFEPROD.PT_GM_CLAIM_ESTIMATE_IDX_002
     ON LIFEPROD.PT_GM_CLAIM_ESTIMATE
        (CE_TREAT_CODE,
         CE_CEMP_SYS_ID)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX LIFEPROD.PT_GM_CLAIM_ESTIMATE_IDX_011
     ON LIFEPROD.PT_GM_CLAIM_ESTIMATE
        (CE_REF_NO,
         CE_CEMP_SYS_ID)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX LIFEPROD.PIX_PT_GM_CLAIM_PAID
     ON LIFEPROD.PT_GM_CLAIM_PAID
        (CP_CEMP_SYS_ID,
         CP_APPRV_STATUS,
         CP_CUST_CODE,
         CP_PAY_DT,
         CP_LC_PAY_AMT,
         CP_FC_PAY_AMT,
         CP_CLM_TYPE)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 852K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX LIFEPROD.PT_GM_POL_EMPLOYEE_IDX_003
     ON LIFEPROD.PT_GM_POL_EMPLOYEE
        (PEMP_EMP_ID,
         PEMP_SYS_ID,
         PEMP_NAME)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX LIFEPROD.PT_GM_POL_EMP_DEPND_IDX_004
     ON LIFEPROD.PT_GM_POL_EMP_DEPND
        (PEMPD_DEPND_ID,
         PEMPD_DEPND_NAME)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX PREMPROD.PM_CUSTOMER_IDX_009
     ON PREMPROD.PM_CUSTOMER
        (CUST_NAME)
    TABLESPACE PREMIDXTAB
    PCTFREE 10;

CREATE INDEX PREMPROD.PT_CLAIM_IDX_021
     ON PREMPROD.PT_CLAIM
        (CLM_CLAIM_NO,
         CLM_POL_NO,
         CLM_SYS_ID,
         CLM_CLOSE_FLAG,
         CLM_CDS_CODE)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;
/*
CREATE UNIQUE INDEX PREMPROD.PIX_POL_6
     ON PREMPROD.PT_POLICY
        (POL_SYS_ID,
         POL_END_NO_IDX,
         POL_NO)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 10
    STORAGE (
        INITIAL 14160K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);
*/
CREATE INDEX PREMPROD.PT_RI_PREM_ALLOC_IDX_013
     ON PREMPROD.PT_RI_PREM_ALLOC
        (RPA_UW_YEAR,
         RPA_SRNO,
         RPA_RC_SYS_ID,
         RPA_POL_SYS_ID,
         RPA_END_NO_IDX)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PT_RI_PREM_ALLOC_IDX_014
     ON PREMPROD.PT_RI_PREM_ALLOC
        (RPA_RC_SYS_ID,
         RPA_SRNO,
         RPA_END_NO_IDX)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PT_VEHICLE_IDX_008
     ON PREMPROD.PT_VEHICLE
        (VEH_CHASSIS_NO,
         VEH_POL_SYS_ID,
         VEH_ENTRY_DT,
         VEH_EXIT_DT)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX LIFEPROD.MENU_MENUS_IDX_009
     ON LIFEPROD.MENU_MENUS
        (MENU_ID,
         MENU_SEQ_NO)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX LIFEPROD.MENU_MENUS_IDX_010
     ON LIFEPROD.MENU_MENUS
        (MENU_PARENT_ID,
         MENU_ID,
         MENU_SEQ_NO)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX LIFEPROD.MENU_USER_IDX_014
     ON LIFEPROD.MENU_USER
        (USER_ID)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX LIFEPROD.MENU_USER_MENUS_IDX_011
     ON LIFEPROD.MENU_USER_MENUS
        (UM_GROUP_ID,
         UM_MENU_ID)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX LIFEPROD.PIX_PH_GM_POLICY
     ON LIFEPROD.PH_GM_POLICY
        (POLGMH_SYS_ID,
         POLGMH_END_NO_IDX,
         POLGMH_O_FM_DT,
         POLGMH_O_TO_DT,
         POLGMH_N_FM_DT,
         POLGMH_N_TO_DT,
         POLGMH_O_UW_YEAR,
         POLGMH_N_UW_YEAR)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 40K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX LIFEPROD.PH_GM_POL_BENEFIT_IDX_008
     ON LIFEPROD.PH_GM_POL_BENEFIT
        (PBNFH_N_BNF_CODE,
         PBNFH_POLGM_SYS_ID,
         PBNFH_OC_CODE,
         PBNFH_END_NO_IDX,
         PBNFH_SYS_ID,
         PBNFH_N_LC_LIMIT)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;
/*
CREATE INDEX LIFEPROD.PIX_PH_GM_POL_EMPLOYEE
     ON LIFEPROD.PH_GM_POL_EMPLOYEE
        (PEMPH_SYS_ID,
         PEMPH_END_NO_IDX,
         PEMPH_O_OC_CODE)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 9616K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);
*/
CREATE INDEX LIFEPROD.PIX_ADS_2
     ON LIFEPROD.PM_APPR_DEPT_SETUP
        (ADS_DEPT_CODE,
         ADS_DIVN_CODE,
         ADS_USER_ID,
         ADS_FRZ_FLAG)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 16K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX LIFEPROD.PM_CURRENCY_IDX_016
     ON LIFEPROD.PM_CURRENCY
        (CURR_CODE)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX LIFEPROD.PM_GM_DED_AREA_IDX_019
     ON LIFEPROD.PM_GM_DED_AREA
        (DA_AREA_CODE,
         DA_DED_CODE)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX LIFEPROD.PP_ITEM_HINT_IDX_012
     ON LIFEPROD.PP_ITEM_HINT
        (IH_MODULE_NAME,
         IH_TYPE,
         IH_BLOCK_NAME,
         IH_ITEM_NAME)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX LIFEPROD.PS_GM_CLAIM_LIMITS_IDX_013
     ON LIFEPROD.PS_GM_CLAIM_LIMITS
        (CL_EMP_SYS_ID,
         CL_BNF_CODE,
         CL_UW_YEAR,
         CL_POLGM_SYS_ID,
         CL_CLAIM_AMT,
         CL_BNF_LIMIT,
         CL_SBNF_CODE)
    TABLESPACE LIFE
    PCTFREE 10;
/*
CREATE INDEX LIFEPROD.PIX_PT_GM_CLAIM_1
     ON LIFEPROD.PT_GM_CLAIM
        (CLM_POLGM_SYS_ID,
         CLM_SYS_ID)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 10
    STORAGE (
        INITIAL 64K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX LIFEPROD.PIX_PT_GM_CLAIM_2
     ON LIFEPROD.PT_GM_CLAIM
        (CLM_POL_NO,
         CLM_SYS_ID,
         CLM_CLM_NO)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 10
    STORAGE (
        INITIAL 64K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);
*/
CREATE INDEX LIFEPROD.PIX_PT_GM_CLAIM_DEDUCTIBLE
     ON LIFEPROD.PT_GM_CLAIM_DEDUCTIBLE
        (CD_CEMP_SYS_ID,
         CD_BNF_CODE,
         CD_DEDB_CODE)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 10
    STORAGE (
        INITIAL 696K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX LIFEPROD.PT_GM_CLAIM_DISCOUNT_IDX_017
     ON LIFEPROD.PT_GM_CLAIM_DISCOUNT
        (CD_CEMP_SYS_ID)
    TABLESPACE FIN7IDXTAB
    PCTFREE 10;
/*
CREATE INDEX LIFEPROD.PIX_PT_GM_CLAIM_EMP_1
     ON LIFEPROD.PT_GM_CLAIM_EMP
        (CEMP_CLM_SYS_ID,
         CEMP_SYS_ID,
         CEMP_PEMP_SYS_ID,
         CEMP_PEMPD_SYS_ID,
         CEMP_DOA,
         CEMP_FC_NET_CLM_PAID,
         CEMP_REF_NO)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 10
    STORAGE (
        INITIAL 856K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX LIFEPROD.PT_GM_CLAIM_EMP_IDX_001
     ON LIFEPROD.PT_GM_CLAIM_EMP
        (CEMP_DOA,
         CEMP_PEMPD_DEPND_ID,
         CEMP_PEMP_EMP_ID,
         CEMP_CLM_SYS_ID,
         CEMP_FC_NET_CLM_PAID,
         CEMP_REF_NO)
    TABLESPACE LIFE
    PCTFREE 10;
*/
CREATE INDEX LIFEPROD.PT_GM_CLAIM_EMP_IDX_007
     ON LIFEPROD.PT_GM_CLAIM_EMP
        (CEMP_REF_NO,
         CEMP_CLM_SYS_ID,
         CEMP_DOA,
         CEMP_PEMP_EMP_ID)
    TABLESPACE LIFE
    PCTFREE 10;

CREATE INDEX LIFEPROD.PIX_PT_GM_CLAIM_ESTIMATE
     ON LIFEPROD.PT_GM_CLAIM_ESTIMATE
        (CE_CEMP_SYS_ID,
         CE_STATUS,
         CE_TREAT_CODE)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 10
    STORAGE (
        INITIAL 704K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);
/*
CREATE INDEX LIFEPROD.PT_GM_CLAIM_ESTIMATE_IDX_002
     ON LIFEPROD.PT_GM_CLAIM_ESTIMATE
        (CE_TREAT_CODE,
         CE_CEMP_SYS_ID)
    TABLESPACE LIFE
    PCTFREE 10;
*/
CREATE UNIQUE INDEX LIFEPROD.PT_GM_CLAIM_ESTIMATE_IDX_022
     ON LIFEPROD.PT_GM_CLAIM_ESTIMATE
        (CE_SYS_ID,
         CE_STATUS,
         CE_LC_CLM_AMT,
         CE_LC_DEDUCTION)
    TABLESPACE LIFE
    PCTFREE 10;
/*
CREATE INDEX LIFEPROD.PIX_PT_GM_CLAIM_PAID
     ON LIFEPROD.PT_GM_CLAIM_PAID
        (CP_CEMP_SYS_ID,
         CP_PAY_DT)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 856K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);
*/
CREATE INDEX LIFEPROD.PT_GM_POLICY_IDX_005
     ON LIFEPROD.PT_GM_POLICY
        (POLGM_CLASS_CODE)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE UNIQUE INDEX LIFEPROD.PT_GM_POLICY_IDX_015
     ON LIFEPROD.PT_GM_POLICY
        (POLGM_SYS_ID,
         POLGM_FM_DT,
         POLGM_TO_DT,
         POLGM_UW_YEAR,
         POLGM_END_NO_IDX)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX LIFEPROD.PT_GM_POLICY_IDX_020
     ON LIFEPROD.PT_GM_POLICY
        (POLGM_APPRV_STATUS,
         POLGM_NO,
         POLGM_CUST_NAME,
         POLGM_ISSUE_DT)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX LIFEPROD.PIX_PT_GM_POL_BENEFIT_2
     ON LIFEPROD.PT_GM_POL_BENEFIT
        (PBNF_BNF_CODE,
         PBNF_POLGM_SYS_ID,
         PBNF_OC_CODE)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 32K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX LIFEPROD.PT_GM_POL_BENEFIT_IDX_018
     ON LIFEPROD.PT_GM_POL_BENEFIT
        (PBNF_OC_CODE,
         PBNF_SYS_ID,
         PBNF_BNF_CODE)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX LIFEPROD.PIX_PT_GM_POL_EMPLOYEE
     ON LIFEPROD.PT_GM_POL_EMPLOYEE
        (PEMP_POLGM_SYS_ID,
         PEMP_NAME,
         PEMP_EMP_ID)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 296K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);
/*
CREATE INDEX LIFEPROD.PT_GM_POL_EMPLOYEE_IDX_003
     ON LIFEPROD.PT_GM_POL_EMPLOYEE
        (PEMP_EMP_ID,
         PEMP_SYS_ID,
         PEMP_NAME)
    TABLESPACE LIFE
    PCTFREE 0;
*/
CREATE INDEX LIFEPROD.PT_GM_POL_EMP_DEPND_IDX_004
     ON LIFEPROD.PT_GM_POL_EMP_DEPND
        (PEMPD_DEPND_ID,
         PEMPD_PEMP_SYS_ID,
         PEMPD_ENTRY_DT,
         PEMPD_EXIT_DT,
         PEMPD_DEPND_NAME)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX LIFEPROD.PH_GM_POL_EMPLOYEE_IDX_021
     ON LIFEPROD.PH_GM_POL_EMPLOYEE
        (PEMPH_POLGM_SYS_ID,
         PEMPH_N_EMP_ID,
         PEMPH_N_NAME)
    TABLESPACE LIFE
    PCTFREE 0;
/*
CREATE INDEX LIFEPROD.PIX_PT_GM_CLAIM_2
     ON LIFEPROD.PT_GM_CLAIM
        (CLM_POL_NO,
         CLM_SYS_ID,
         CLM_CLM_NO)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 60K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX LIFEPROD.PIX_PT_GM_CLAIM_EMP_1
     ON LIFEPROD.PT_GM_CLAIM_EMP
        (CEMP_CLM_SYS_ID,
         CEMP_SYS_ID,
         CEMP_PEMP_SYS_ID,
         CEMP_PEMPD_SYS_ID,
         CEMP_DOA,
         CEMP_FC_NET_CLM_PAID,
         CEMP_REF_NO)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 852K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);
*/
CREATE INDEX LIFEPROD.PT_GM_CLAIM_EMP_IDX_010
     ON LIFEPROD.PT_GM_CLAIM_EMP
        (CEMP_DOA,
         CEMP_FC_NET_CLM_PAID,
         CEMP_REF_NO)
    TABLESPACE LIFE
    PCTFREE 0;
/*
CREATE INDEX LIFEPROD.PT_GM_CLAIM_ESTIMATE_IDX_011
     ON LIFEPROD.PT_GM_CLAIM_ESTIMATE
        (CE_TREAT_CODE,
         CE_CEMP_SYS_ID)
    TABLESPACE LIFE
    PCTFREE 0;
*/
CREATE INDEX LIFEPROD.PT_GM_CLAIM_ESTIMATE_IDX_017
     ON LIFEPROD.PT_GM_CLAIM_ESTIMATE
        (CE_REF_NO,
         CE_CEMP_SYS_ID)
    TABLESPACE LIFE
    PCTFREE 0;
/*
CREATE INDEX LIFEPROD.PIX_PT_GM_CLAIM_PAID
     ON LIFEPROD.PT_GM_CLAIM_PAID
        (CP_CEMP_SYS_ID,
         CP_APPRV_STATUS,
         CP_CUST_CODE,
         CP_PAY_DT,
         CP_LC_PAY_AMT,
         CP_FC_PAY_AMT)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE LIFE
    PCTFREE 0
    STORAGE (
        INITIAL 852K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);
*/
CREATE INDEX LIFEPROD.PT_GM_POL_EMPLOYEE_IDX_012
     ON LIFEPROD.PT_GM_POL_EMPLOYEE
        (PEMP_EMP_ID,
         PEMP_SYS_ID,
         PEMP_NAME)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX LIFEPROD.PT_GM_POL_EMP_DEPND_IDX_013
     ON LIFEPROD.PT_GM_POL_EMP_DEPND
        (PEMPD_DEPND_ID,
         PEMPD_DEPND_NAME)
    TABLESPACE LIFE
    PCTFREE 0;

CREATE INDEX PREMPROD.PH_POLICY_IDX_018
     ON PREMPROD.PH_POLICY
        (POLH_DIVN_CODE,
         POLH_DEPT_CODE)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PM_CUSTOMER_IDX_015
     ON PREMPROD.PM_CUSTOMER
        (CUST_NAME)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.AIR_POL_SYS_ID
     ON PREMPROD.PT_AIRCRAFT
        (AIR_POL_SYS_ID,
         AIR_CURR_CODE)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 20K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.PT_CLAIM_IDX_001
     ON PREMPROD.PT_CLAIM
        (CLM_POL_SYS_ID,
         CLM_SYS_ID,
         CLM_POL_NO)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PT_CLAIM_IDX_005
     ON PREMPROD.PT_CLAIM
        (CLM_CDS_CODE,
         CLM_POL_SYS_ID,
         CLM_SYS_ID)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PT_CLAIM_IDX_007
     ON PREMPROD.PT_CLAIM
        (CLM_DEPT_CODE,
         CLM_SYS_ID)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PT_CLAIMS_TP_IDX_009
     ON PREMPROD.PT_CLAIMS_TP
        (CTP_TP_NAME)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.FK_CE_CLM_IDX
     ON PREMPROD.PT_CLAIM_ESTIMATE
        (CE_CLM_SYS_ID,
         CE_SYS_ID,
         CE_EST_CURR_CODE,
         CE_EST_TYPE,
         CE_TYPE_DESC)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 4620K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.PT_CLAIM_ESTIMATE_IDX_002
     ON PREMPROD.PT_CLAIM_ESTIMATE
        (CE_FRZ_FLAG,
         CE_EST_CURR_CODE,
         CE_SYS_ID,
         CE_EST_TYPE,
         CE_TYPE_DESC)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PT_CLAIM_ESTIMATE_IDX_006
     ON PREMPROD.PT_CLAIM_ESTIMATE
        (CE_EST_CURR_CODE,
         CE_SYS_ID,
         CE_EST_TYPE,
         CE_TYPE_DESC)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PIX_CP_3
     ON PREMPROD.PT_CLAIM_PAID
        (CP_CUST_CODE,
         CP_CE_SYS_ID,
         CP_PAID_DT)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 2860K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.PT_CLAIM_PAID_IDX_003
     ON PREMPROD.PT_CLAIM_PAID
        (CP_APPR_FLAG,
         CP_CLM_SYS_ID,
         CP_CE_SYS_ID,
         CP_CUST_CODE,
         CP_PAID_DT,
         CP_FC_PAID_AMT,
         CP_LC_PAID_AMT)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.OP_POL_SYS_ID
     ON PREMPROD.PT_OPEN_POLICY
        (OP_POL_SYS_ID,
         OP_SYS_ID)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 20K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.FK_POL_SC_IDX
     ON PREMPROD.PT_POLICY
        (POL_SC_CODE,
         POL_SYS_ID,
         POL_CUST_CODE)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 15892K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

/*
CREATE UNIQUE INDEX PREMPROD.PIX_POL_6
     ON PREMPROD.PT_POLICY
        (POL_SYS_ID,
         POL_END_NO_IDX,
         POL_NO)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 14160K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);
*/

CREATE INDEX PREMPROD.PT_POL_BROKER_IDX_008
     ON PREMPROD.PT_POL_BROKER
        (PB_SYS_ID)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.FK_PCVR_CURR_IDX
     ON PREMPROD.PT_POL_COVER
        (PCVR_SI_CURR_CODE,
         PCVR_POL_SYS_ID)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 15892K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.PCVR_POL_SYS_ID
     ON PREMPROD.PT_POL_COVER
        (PCVR_POL_SYS_ID,
         PCVR_CODE,
         PCVR_LC_SI,
         PCVR_LC_PREM)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 11280K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.RISK_POL_SYS_ID
     ON PREMPROD.PT_RISK
        (RISK_POL_SYS_ID,
         RISK_SI_CURR_CODE)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 1032K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.PT_RI_PREM_ALLOC_IDX_019
     ON PREMPROD.PT_RI_PREM_ALLOC
        (RPA_UW_YEAR,
         RPA_SRNO,
         RPA_RC_SYS_ID,
         RPA_POL_SYS_ID,
         RPA_END_NO_IDX)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PT_RI_PREM_ALLOC_IDX_020
     ON PREMPROD.PT_RI_PREM_ALLOC
        (RPA_RC_SYS_ID,
         RPA_SRNO,
         RPA_END_NO_IDX)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.SHIP_POL_SYS_ID
     ON PREMPROD.PT_SHIPMENT
        (SHIP_POL_SYS_ID,
         SHIP_LC_NO,
         SHIP_BANK_NAME,
         SHIP_SYS_ID)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 1032K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.SG_SHIP_SYS_ID
     ON PREMPROD.PT_SHIP_GOOD
        (SG_SHIP_SYS_ID,
         SG_CURR_CODE)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 1260K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.PIX_SG_2
     ON PREMPROD.PT_SHIP_GOOD
        (SG_OP_SYS_ID,
         SG_CURR_CODE)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 20K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.PT_SHIP_GOOD_IDX_022
     ON PREMPROD.PT_SHIP_GOOD
        (SG_CODE,
         SG_OP_SYS_ID,
         SG_SHIP_SYS_ID)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.VEH_POL_SYS_ID
     ON PREMPROD.PT_VEHICLE
        (VEH_POL_SYS_ID,
         VEH_SYS_ID,
         VEH_REGN_NO,
         VEH_CHASSIS_NO,
         VEH_VEHICLE_ID,
         VEH_CURR_CODE)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 9232K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.PT_VEHICLE_IDX_014
     ON PREMPROD.PT_VEHICLE
        (VEH_CHASSIS_NO,
         VEH_POL_SYS_ID,
         VEH_ENTRY_DT,
         VEH_EXIT_DT)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.VES_POL_SYS_ID
     ON PREMPROD.PT_VESSEL
        (VES_POL_SYS_ID,
         VES_CURR_CODE)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 10
    STORAGE (
        INITIAL 1032K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.PT_VESSEL_IDX_016
     ON PREMPROD.PT_VESSEL
        (VES_SYS_ID)
    TABLESPACE PREMIDXTAB
    PCTFREE 10;

--------------------------------------------------------------------------------
--  CREATE Index Recommendations
--------------------------------------------------------------------------------

/*
CREATE INDEX PREMPROD.PT_CLAIM_IDX_001
     ON PREMPROD.PT_CLAIM
        (CLM_POL_SYS_ID,
         CLM_SYS_ID,
         CLM_POL_NO)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PT_CLAIM_IDX_005
     ON PREMPROD.PT_CLAIM
        (CLM_CDS_CODE,
         CLM_POL_SYS_ID,
         CLM_SYS_ID)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PT_CLAIM_IDX_007
     ON PREMPROD.PT_CLAIM
        (CLM_DEPT_CODE,
         CLM_SYS_ID)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.FK_CE_CLM_IDX
     ON PREMPROD.PT_CLAIM_ESTIMATE
        (CE_CLM_SYS_ID,
         CE_SYS_ID,
         CE_EST_CURR_CODE,
         CE_EST_TYPE,
         CE_TYPE_DESC)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 4620K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.PT_CLAIM_ESTIMATE_IDX_002
     ON PREMPROD.PT_CLAIM_ESTIMATE
        (CE_FRZ_FLAG,
         CE_EST_CURR_CODE,
         CE_SYS_ID,
         CE_EST_TYPE,
         CE_TYPE_DESC)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PT_CLAIM_ESTIMATE_IDX_006
     ON PREMPROD.PT_CLAIM_ESTIMATE
        (CE_EST_CURR_CODE,
         CE_SYS_ID,
         CE_EST_TYPE,
         CE_TYPE_DESC)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PIX_CP_3
     ON PREMPROD.PT_CLAIM_PAID
        (CP_CUST_CODE,
         CP_CE_SYS_ID,
         CP_PAID_DT)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 2860K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.PT_CLAIM_PAID_IDX_003
     ON PREMPROD.PT_CLAIM_PAID
        (CP_APPR_FLAG,
         CP_CLM_SYS_ID,
         CP_CE_SYS_ID,
         CP_CUST_CODE,
         CP_PAID_DT,
         CP_FC_PAID_AMT,
         CP_LC_PAID_AMT)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.FK_POL_SC_IDX
     ON PREMPROD.PT_POLICY
        (POL_SC_CODE,
         POL_SYS_ID,
         POL_CUST_CODE)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 15892K
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645);
*/
CREATE INDEX PREMPROD.PT_POL_BROKER_IDX_008
     ON PREMPROD.PT_POL_BROKER
        (PB_SYS_ID)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;
