-- ***************************************************************************
-- File: 5_43.sql
--
-- Developed By TUSC
--
-- Disclaimer: Neither Osborne/McGraw-Hill, TUSC, nor the author warrant
--             that this source code is error-free. If any errors are
--             found in this source code, please report them to TUSC at
--             (630)960-2909 ext 1011 or trezzoj@tusc.com.
-- ***************************************************************************

SPOOL 5_43.lis

CREATE SEQUENCE system_error_id NOCACHE;

CREATE TABLE system_errors
   (system_error_id  NUMBER(10,0), package_name  VARCHAR2(50),
    procedure_name  VARCHAR2(50), execution_location  varchar2(20),
    oracle_error_text  VARCHAR2(200), 
    additional_information  VARCHAR2(2000),
    call_stack   VARCHAR2(2000), error_stack  VARCHAR2(2000),
    insert_time  DATE, insert_user  VARCHAR2(30));

COMMENT ON TABLE system_errors IS 
   'Errors generated by stored packages.';
COMMENT ON COLUMN system_errors.system_error_id IS 
   'The system-wide ID to identify a system error. Useful for 
    determining the order in which errors were encountered and 
    logged.';
COMMENT ON COLUMN system_errors.package_name IS 'The package name.';
COMMENT ON COLUMN system_errors.procedure_name IS 
   'The procedure/function name.';
COMMENT ON COLUMN system_errors.execution_location IS 
   'A reference to a location in the executing code.';
COMMENT ON COLUMN system_errors.oracle_error_text IS 
   'The text of the Oracle error message.';
COMMENT ON COLUMN system_errors.additional_information IS 
   'Any pertinent information the developer may be trapping by the 
   error handler.';
COMMENT ON COLUMN system_errors.call_stack IS 
   'The call stack at the time of the error.';
COMMENT ON COLUMN system_errors.error_stack IS 
   'The error stack at the time of the error.';
COMMENT ON COLUMN system_errors.insert_time IS 
   'The date and time of record insertion.';
COMMENT ON COLUMN system_errors.insert_user IS 
   'The user inserting the record.';

SPOOL OFF
