--DROP INDEX FINAL7.NUX_MENU_MENUS_01;

--DROP INDEX PREMPROD.NUX_MENU_MENUS_01;

--DROP INDEX PREMPROD.IX_MENU_MENUS_02;

--DROP INDEX PREMPROD.UX_MENU_MENUS_1;

--DROP INDEX PREMPROD.IX_USER_1;

--DROP INDEX PREMPROD.IX_MENU_USER_MENUS_02;

--DROP INDEX PREMPROD.IX_MENU_USER_MENUS_01;

DROP INDEX PREMPROD.VEH_POL_SYS_ID;

ALTER TABLESPACE "SYSTEM" COALESCE;


CREATE INDEX FINAL7.NUX_MENU_MENUS_IDX_01
     ON FINAL7.MENU_MENUS
        (MENU_PARENT_ID,
         MENU_ID,
         MENU_DISP_SEQ_NO,
         MENU_SEQ_NO)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE FIN7IDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 32K
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX FINAL7.MENU_USER_IDX_008
     ON FINAL7.MENU_USER
        (USER_ID,
         USER_GROUP_ID)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.LOOKUP_IDX_001
     ON PREMPROD.LOOKUP
        (NUMBERVALUE,
         ARABTEXT,
         NUMBERTEXT)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.NUX_MENU_MENUS_IDX_01
     ON PREMPROD.MENU_MENUS
        (MENU_PARENT_ID,
         MENU_ID,
         MENU_SEQ_NO)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 0
    STORAGE (
        INITIAL 60K
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE UNIQUE INDEX PREMPROD.MENU_REPORT_USER_PRI_IDX_005
     ON PREMPROD.MENU_REPORT_USER_PRINTER
        (RUP_REPORT_ID,
         RUP_USER_ID,
         RUP_PRN_CODE,
         RUP_PF_CODE,
         RUP_COPIES,
         RUP_OVERRIDE_YN)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE UNIQUE INDEX PREMPROD.MENU_USER_IDX_007
     ON PREMPROD.MENU_USER
        (USER_ID,
         USER_PRN_CODE,
         USER_PF_CODE,
         USER_COPIES,
         USER_OVERRIDE_YN)
    TABLESPACE PREMIDXTAB
    PCTFREE 10;

CREATE INDEX PREMPROD.PP_BOILERPLATE_TEXT_IDX_002
     ON PREMPROD.PP_BOILERPLATE_TEXT
        (BT_MODULE_NAME,
         BT_BLOCK_NAME,
         BT_ITEM_NAME,
         BT_FOR_TEXT)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PP_ITEM_HINT_IDX_003
     ON PREMPROD.PP_ITEM_HINT
        (IH_TYPE,
         IH_MODULE_NAME,
         IH_BLOCK_NAME,
         IH_ITEM_NAME,
         IH_FOR_HINT,
         IH_ENG_HINT)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PP_SYSTEM_IDX_014
     ON PREMPROD.PP_SYSTEM
        (PS_CODE,
         PS_TYPE,
         PS_VALUE)
    TABLESPACE PREMIDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.PP_WINDOW_TITLE_IDX_004
     ON PREMPROD.PP_WINDOW_TITLE
        (WT_MODULE_NAME,
         WT_WINDOW_NAME,
         WT_FOR_TITLE)
    TABLESPACE FIN7IDXTAB
    PCTFREE 0;

CREATE INDEX PREMPROD.VEH_POL_SYS_ID
     ON PREMPROD.PT_VEHICLE
        (VEH_POL_SYS_ID,
         VEH_SYS_ID,
         VEH_REGN_NO,
         VEH_CHASSIS_NO,
         VEH_VEHICLE_ID,
         VEH_DOC_NO,
         VEH_ENTRY_DT,
         VEH_EXIT_DT)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 10
    STORAGE (
        INITIAL 9232K
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.PT_VEHICLE_IDX_007
     ON PREMPROD.PT_VEHICLE
        (VEH_CHASSIS_NO)
    LOGGING
    INITRANS 2
    MAXTRANS 255
    TABLESPACE PREMIDXTAB
    PCTFREE 10
    STORAGE (
        INITIAL 64K
        MINEXTENTS 1
        MAXEXTENTS 2147483645);

CREATE INDEX PREMPROD.PT_VEHICLE_IDX_009
     ON PREMPROD.PT_VEHICLE
        (VEH_REGN_NO)
    TABLESPACE PREMIDXTAB
    PCTFREE 10;

