column column_len format a44                                                                                                                                                                                                                              
column column_type format a9                                                                                                                                                                                                                              
column column_name format a30                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                          
prompt Creating SELECT file                                                                                                                                                                                                                               
prompt Please wait . . .                                                                                                                                                                                                                                  
set termout off                                                                                                                                                                                                                                           
spool                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                          
spool off                                                                                                                                                                                                                                                 
